### PR TITLE
Add Open Source License

### PR DESCRIPTION
**Pull request by lrinQVQ**
* Add Open Source Software License and Source Url
* TTKMusicplayer and Mcool is Chinese developers Software
* Change some Website use https,If the Website support

### CODE REVIEW

**Comment by EMLVIRUS** [comment]
麻烦可以更新一下格式吗？在[issue](https://github.com/EMLVIRUS/Amazing-Windows-Apps/issues/108#issuecomment-303294541)里我有提到

此外logo的顺序能否按照guidelines的说明？

原谅我强迫症（此外GitBook抽风💊，暂时无事可干）

**Comment by lrinQVQ** [comment]
2333okok

**Comment by lrinQVQ** [comment]
ok 改好了2333

**Comment by EMLVIRUS** [comment]
@lrinQVQ 😘

**Pull request merged**
